# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rgig <- function(N, lambda, psi, chi, eps = 0.5, K = 0L) {
    .Call('_GIGcpp_rgig', PACKAGE = 'GIGcpp', N, lambda, psi, chi, eps, K)
}

